/* Tarjetas de sellos: reads and mutations always go to the tenant-scoped API. */
(() => {
  const root=document.getElementById('stampCardsWorkspace');if(!root)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v||0));
  const number=v=>Number(v||0).toLocaleString('es-CO');
  const date=v=>v?new Date(v).toLocaleDateString('es-CO'):'';
  const label={ACTIVE:'Activo',PAUSED:'Pausado',ARCHIVED:'Archivado',REDEEMED:'Canjeado',CANCELLED:'Anulado',EXPIRED:'Vencido'};
  const apiCall=(path,method='GET',body)=>api(`/api/business/stamp-cards${path}`,{method,headers:authHeaders(),noClientCache:true,...(body?{body:JSON.stringify(body)}:{})});
  let ctx={programs:[],business:{}},memberRows=[],historyRows=[],memberOffset=0,historyOffset=0,requestVersion=0;
  let filters={from:new Date(Date.now()-29*86400000).toISOString().slice(0,10),to:new Date().toISOString().slice(0,10),program_id:'',search:''};
  function query(extra={}){const q=new URLSearchParams({...filters,...extra});if(!q.get('program_id'))q.delete('program_id');return q.toString();}
  function message(text,error=false){const node=root.querySelector('.sc-message');if(node){node.textContent=text;node.classList.toggle('error',error);}}
  function logo(){const src=ctx.business.logo_data_url||ctx.business.logo_url;return src&&/^(data:image\/(png|jpeg|webp|gif);base64,|https?:\/\/|\/)/i.test(src)?`<img src="${esc(src)}" alt="Logo de ${esc(ctx.business.name)}">`:'';}
  function art(p){return `<div class="sc-card-art"><div class="sc-brand">${logo()}<span>${esc(ctx.business.name||'Tu negocio')}</span></div><h4>${esc(p.name||'Cada visita cuenta')}</h4><p>${esc(p.benefit_value?.label||'Un beneficio para volver')}</p><div class="sc-dots">${Array.from({length:Math.min(Number(p.stamps_required)||8,50)},(_,i)=>`<span class="sc-dot">${i+1}</span>`).join('')}</div></div>`;}
  function shell(){root.innerHTML=`<header class="sc-hero"><div><span class="sc-eyebrow">Optimiza · Fidelización</span><h2>Tarjeta de sellos</h2><p>Dales una razón para volver. Convierte las compras de tus clientes en sellos y los sellos en un beneficio de tu negocio.</p></div><div class="sc-actions"><button data-action="enroll">Entregar tarjeta</button><button class="sc-primary" data-action="create">Crear programa</button></div></header>
    <div class="sc-message" role="status" aria-live="polite"></div>
    <form class="sc-toolbar" id="scFilters"><label>Programa<select name="program_id"><option value="">Todos los programas</option></select></label><label>Desde<input type="date" name="from" required value="${filters.from}"></label><label>Hasta<input type="date" name="to" required value="${filters.to}"></label><button type="submit">Actualizar</button><span id="scBalance" class="sc-badge"></span></form>
    <div id="scMetrics" class="sc-kpis" aria-live="polite"><p>Cargando indicadores…</p></div>
    <div class="sc-charts"><article class="sc-panel"><h3>Sellos a través del tiempo</h3><p>Compras identificadas y visitas registradas en el periodo.</p><div id="scTrend"></div></article><article class="sc-panel"><h3>Del sello al beneficio</h3><p>Completar, generar el ticket y canjearlo son pasos distintos.</p><div id="scFunnel"></div></article></div>
    <div class="sc-note" id="scMethod">Los retornos son visitas selladas posteriores a la primera visita registrada de cada cliente. Las ventas vinculadas muestran asociación con el programa; no prueban ventas adicionales causadas por él. Las visitas manuales no suman ingresos.</div>
    <article class="sc-panel"><div class="sc-panel-head"><div><h3>Tus programas</h3><p>Crea la promesa y deja que cada compra acerque a tus clientes.</p></div></div><div id="scPrograms" class="sc-programs"></div></article>
    <article class="sc-panel"><div class="sc-panel-head"><div><h3>Tarjetas de tus clientes</h3><p>Comparte el enlace personal para que cada cliente consulte sus sellos.</p></div><form id="scSearch" class="sc-actions sc-inline-search"><input type="search" name="search" aria-label="Buscar cliente por nombre o documento" placeholder="Nombre o documento" maxlength="120"><button>Buscar</button></form></div><div id="scMembers"></div></article>
    <article class="sc-panel"><div class="sc-panel-head"><div><h3>Historial de sellos</h3><p>Origen, ventas, anulaciones y estado del beneficio.</p></div><button data-action="export">Exportar página CSV</button></div><div id="scHistory"></div></article>`;
    root.querySelector('#scFilters').addEventListener('submit',e=>{e.preventDefault();Object.assign(filters,Object.fromEntries(new FormData(e.target)));memberOffset=historyOffset=0;load();});
    root.querySelector('#scSearch').addEventListener('submit',e=>{e.preventDefault();filters.search=new FormData(e.target).get('search');memberOffset=historyOffset=0;loadLists();});
  }
  async function load(){const version=++requestVersion;try{
    const [context,data]=await Promise.all([apiCall('/context'),apiCall(`/dashboard?${query()}`)]);if(version!==requestVersion)return;
    ctx=context;root.querySelector('#scBalance').textContent=`${number(ctx.ticket_balance)} tickets disponibles`;
    const select=root.querySelector('[name="program_id"]');select.innerHTML=`<option value="">Todos los programas</option>${ctx.programs.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}${(ctx.deleted_programs||[]).map(p=>`<option value="${p.id}">${esc(p.name)} · Eliminado</option>`).join('')}`;select.value=filters.program_id;
    renderMetrics(data);renderPrograms();await loadLists();
  }catch(error){message(error.message,true);}}
  function renderMetrics({metrics:m,trend}){
    const stats=[['Clientes activos',number(m.active_customers),`${number(m.total_customers)} inscritos en total`],['Visitas de retorno',number(m.return_visits),'Visitas posteriores a la primera'],['Clientes que volvieron',`${number(m.return_rate)} %`,`${number(m.returning_customers)} clientes del periodo`],['Ventas vinculadas',money(m.linked_sales),'Compras con sello válido'],['Tarjetas completadas',number(m.completed),`${number(m.pending)} listas para generar beneficio`],['Tickets generados',number(m.issued),'1 ticket Qori por beneficio generado'],['Beneficios canjeados',number(m.redeemed),'Canjes confirmados en el Validador'],['Retorno estimado',m.estimated_return_pct===null?'Sin costo base':`${number(m.estimated_return_pct)} %`,`${money(m.estimated_cost)} en costos configurados`]];
    root.querySelector('#scMetrics').innerHTML=stats.map(([name,value,help])=>`<article class="sc-kpi"><small>${name}</small><strong>${value}</strong><p>${help}</p></article>`).join('');
    const max=Math.max(1,...trend.map(d=>d.stamps));
    root.querySelector('#scTrend').innerHTML=trend.length?`<div class="sc-trend" role="img" aria-label="Sellos diarios: ${esc(trend.map(d=>`${date(d.day)}: ${d.stamps}`).join('; '))}">${trend.map(d=>`<div class="sc-trend-bar" title="${esc(date(d.day))}: ${d.stamps} sellos · ${esc(money(d.sales))}"><span style="height:${Math.round(d.stamps/max*100)}%"></span></div>`).join('')}</div><div class="sc-trend-labels"><span>${date(trend[0].day)}</span><span>${date(trend.at(-1).day)}</span></div>`:'<div class="sc-empty">Aquí verás cómo crece la fidelización cuando registres los primeros sellos.</div>';
    const maxF=Math.max(1,m.completed,m.issued,m.redeemed);root.querySelector('#scFunnel').innerHTML=[['Completadas',m.completed],['Tickets generados',m.issued],['Beneficios canjeados',m.redeemed]].map(([name,n])=>`<div class="sc-funnel-row"><div><span>${name}</span><strong>${number(n)}</strong></div><div class="sc-meter"><span style="width:${Number(n)/maxF*100}%"></span></div></div>`).join('');
    root.querySelector('#scMethod').textContent=`Los retornos son visitas selladas posteriores a la primera registrada de cada cliente. Ventas vinculadas no equivalen a ventas adicionales causadas por el programa. Retorno estimado = (ventas vinculadas − costos configurados) / costos configurados; no incluye margen, impuestos ni otros gastos. Los costos se cuentan al emitir el ticket y al canjear el premio. ${m.needs_review?`${m.needs_review} tarjeta(s) requieren revisión por sellos anulados después de emitir su ticket.`:''}`;
  }
  function renderPrograms(){root.querySelector('#scPrograms').innerHTML=ctx.programs.length?ctx.programs.map(p=>`<article class="sc-card">${art(p)}<div class="sc-card-body"><span class="sc-badge ${p.status!=='ACTIVE'?'warn':''}">${label[p.status]} · ${number(p.members)} clientes</span><p>${p.stamps_required} sellos · ${p.one_per_day?'Máximo uno al día':'Uno por compra'}<br>Compra mínima ${money(p.minimum_purchase)} · Vigencia ${p.card_valid_days} días</p><div class="sc-actions"><button data-action="edit" data-id="${p.id}">Configurar</button><button data-action="enroll" data-id="${p.id}" ${p.status!=='ACTIVE'?'disabled':''}>Entregar tarjeta</button><button data-action="delete" data-id="${p.id}">Eliminar</button></div></div></article>`).join(''):'<div class="sc-empty"><strong>Tu próxima visita empieza aquí.</strong><br>Crea un programa, elige un beneficio y entrega la primera tarjeta. Crear tarjetas y sumar sellos no consume tickets.</div>';}
  async function loadLists(){try{const [members,history]=await Promise.all([apiCall(`/members?${query({offset:memberOffset})}`),apiCall(`/history?${query({offset:historyOffset})}`)]);memberRows=members.members;historyRows=history.events;
    root.querySelector('#scMembers').innerHTML=memberRows.length?`<div class="sc-table-wrap"><table><thead><tr><th>Cliente</th><th>Programa</th><th>Progreso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${memberRows.map(m=>`<tr><td><strong>${esc(m.name)}</strong><small>${esc(m.document_key)}</small></td><td>${esc(m.program_name)}${m.program_deleted_at?'<small>Programa eliminado</small>':''}<small>Tarjeta ${m.cycle_number}</small></td><td><strong>${m.stamps} / ${m.rules.stamps_required}</strong><small>Vence ${date(m.expires_at)}</small></td><td>${m.review_required?'<span class="sc-badge warn">Revisar anulación</span>':esc(m.claimed_at?(label[m.ticket_status]||'Ticket generado'):new Date(m.expires_at)<new Date()?'Vencida':m.stamps>=m.rules.stamps_required?'Lista para beneficio':'En progreso')}</td><td><div class="sc-actions"><button data-action="share" data-id="${m.id}">Compartir</button>${m.program_status==='ACTIVE'&&!m.claimed_at&&m.stamps<m.rules.stamps_required&&new Date(m.expires_at)>new Date()?`<button data-action="stamp" data-id="${m.id}">Sellar visita</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>${pagination('members',memberOffset,25,members.has_more)}`:'<div class="sc-empty">No hay tarjetas con estos filtros. Usa «Entregar tarjeta» para inscribir a un cliente.</div>';
    root.querySelector('#scHistory').innerHTML=historyRows.length?`<div class="sc-table-wrap"><table><thead><tr><th>Fecha / cliente</th><th>Tarjeta</th><th>Sello</th><th>Venta</th><th>Beneficio</th><th>Acción</th></tr></thead><tbody>${historyRows.map(e=>`<tr><td>${date(e.created_at)}<small>${esc(e.name)}</small></td><td>${esc(e.program_name)}<small>Ciclo ${e.cycle_number} · ${e.stamps}/${e.goal}</small></td><td>${e.source==='SALE'?'Compra automática':'Visita manual'}<small>${esc(e.note)}</small>${e.voided_at?`<small>Anulado: ${esc(e.void_reason)}</small>`:''}</td><td>${e.source==='SALE'?money(e.sale_amount):'Sin venta asociada'}</td><td>${esc(e.claimed_at?(label[e.ticket_status]||'Ticket generado'):'Sin emitir')}${e.review_required?'<small>Requiere revisión</small>':''}</td><td>${e.voided_at?'Historial conservado':`<button data-action="void" data-id="${e.id}">Anular sello</button>`}</td></tr>`).join('')}</tbody></table></div>${pagination('history',historyOffset,50,history.has_more)}`:'<div class="sc-empty">Sin movimientos en el periodo seleccionado.</div>';
  }catch(error){message(error.message,true);}}
  function pagination(kind,offset,size,more){return `<div class="sc-pagination"><button data-action="prev-${kind}" ${!offset?'disabled':''}>Anterior</button><span>Página ${Math.floor(offset/size)+1}</span><button data-action="next-${kind}" ${!more?'disabled':''}>Siguiente</button></div>`;}
  function dialog(title,content){document.getElementById('scDialog')?.remove();const d=document.createElement('dialog');d.id='scDialog';d.className='sc-dialog';d.setAttribute('aria-labelledby','scDialogTitle');d.innerHTML=`<header><h3 id="scDialogTitle">${title}</h3><button type="button" aria-label="Cerrar">✕</button></header><div class="sc-dialog-content">${content}<p class="sc-message" role="status" id="scDialogMessage"></p></div>`;document.body.append(d);d.querySelector('header button').onclick=()=>d.close();d.showModal();return d;}
  function field(name,title,value,type='text',extra=''){return `<label>${title}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
  function formTask(d,fn){d.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await fn(new FormData(e.target));}catch(error){const n=d.querySelector('#scDialogMessage');n.textContent=error.message;n.classList.add('error');}finally{button.disabled=false;}});}
  function editor(id){const p=ctx.programs.find(p=>p.id===id)||{stamps_required:8,minimum_purchase:0,one_per_day:true,allow_manual:true,card_valid_days:365,ticket_valid_days:30,reward_cost:0,ticket_cost:0,benefit_type:'FREE_GIFT',benefit_value:{}};
    const d=dialog(id?'Configurar programa':'Crear programa de sellos',`<form><div class="sc-form-grid">${field('name','Nombre del programa',p.name||'','text','required maxlength="120"')}${field('stamps_required','Sellos para completar',p.stamps_required,'number','min="2" max="50" required')}<label>Tipo de beneficio<select name="benefit_type">${[['FREE_GIFT','Producto o servicio gratis'],['PERCENT_DISCOUNT','Descuento porcentual'],['FIXED_AMOUNT_DISCOUNT','Descuento en pesos'],['CUSTOM','Beneficio personalizado']].map(([v,t])=>`<option value="${v}" ${v===p.benefit_type?'selected':''}>${t}</option>`).join('')}</select></label>${field('label','Beneficio que recibirá el cliente',p.benefit_value.label||'','text','required maxlength="240" placeholder="Ej. Un café de la casa"')}${field('benefit_number','Valor del descuento (% o COP)',p.benefit_value.percent||p.benefit_value.amount||0,'number','min="0" step="0.01"')}${field('minimum_purchase','Compra mínima para sumar un sello (COP)',p.minimum_purchase,'number','min="0" step="1" required')}${field('card_valid_days','Vigencia de la tarjeta (días)',p.card_valid_days,'number','min="1" max="3650" required')}${field('ticket_valid_days','Vigencia del ticket generado (días)',p.ticket_valid_days,'number','min="1" max="3650" required')}${field('reward_cost','Costo estimado del premio para tu negocio (COP)',p.reward_cost,'number','min="0" step="1" required')}${field('ticket_cost','Costo de tu ticket Qori (COP)',p.ticket_cost,'number','min="0" step="1" required')}<label class="sc-check"><input type="checkbox" name="one_per_day" ${p.one_per_day?'checked':''}>Máximo un sello por día y cliente (hora de Colombia).</label><label class="sc-check"><input type="checkbox" name="allow_manual" ${p.allow_manual?'checked':''}>Permitir sellos manuales por visitas, con referencia y responsable. Aplica también a las tarjetas ya entregadas.</label><label>Estado<select name="status">${['ACTIVE','PAUSED','ARCHIVED'].map(s=>`<option value="${s}" ${p.status===s?'selected':''}>${label[s]}</option>`).join('')}</select><small>Pausar o archivar detiene nuevas tarjetas y sellos. Los beneficios ya ganados se respetan.</small></label><label>Condiciones para el cliente<textarea name="terms" rows="3" maxlength="4000">${esc(p.terms||'')}</textarea></label><div class="sc-note sc-wide">Cada compra pagada con el documento del cliente suma un sello. Las tarjetas completas deben generar su beneficio e iniciar una nueva para seguir sumando. ${id?'Los cambios de beneficio y metas aplican a nuevas tarjetas; las entregadas conservan sus condiciones. El permiso de sellado manual se actualiza para todas.':'Crear programas y tarjetas no consume tickets. Generar cada beneficio consume 1 ticket.'}</div></div><footer><button class="sc-primary">Guardar programa</button></footer></form>`);
    const type=d.querySelector('[name="benefit_type"]'),amount=d.querySelector('[name="benefit_number"]');function toggle(){amount.closest('label').hidden=!['PERCENT_DISCOUNT','FIXED_AMOUNT_DISCOUNT'].includes(type.value);amount.max=type.value==='PERCENT_DISCOUNT'?'100':'999999999';}type.onchange=toggle;toggle();
    formTask(d,async f=>{const data=Object.fromEntries(f);data.one_per_day=f.has('one_per_day');data.allow_manual=f.has('allow_manual');data.benefit_value={label:data.label,...(data.benefit_type==='PERCENT_DISCOUNT'?{percent:Number(data.benefit_number)}:data.benefit_type==='FIXED_AMOUNT_DISCOUNT'?{amount:Number(data.benefit_number)}:{})};delete data.label;delete data.benefit_number;await apiCall(id?`/programs/${id}`:'/programs',id?'PUT':'POST',data);d.close();await load();message('Programa guardado.');});
  }
  function deleteProgram(id){
    const p=ctx.programs.find(p=>p.id===id);if(!p)return;
    const d=dialog('Eliminar programa de sellos',`<p>Vas a eliminar <strong>${esc(p.name)}</strong>.</p><p>El programa desaparecerá de «Tus programas» y dejará de recibir tarjetas y sellos nuevos.</p><p>Las tarjetas entregadas, el historial y los tickets emitidos se conservarán. Los clientes con una tarjeta completa y vigente podrán generar su beneficio. Puedes consultar los datos usando el filtro de programas eliminados.</p><form><footer><button type="button" data-cancel>Cancelar</button><button class="sc-primary">Eliminar programa</button></footer></form>`);
    d.querySelector('[data-cancel]').onclick=()=>d.close();
    formTask(d,async()=>{await apiCall(`/programs/${id}`,'DELETE');d.close();await load();message('Programa eliminado. Su historial y beneficios ganados se conservan.');});
  }
  function enrollForm(id){const active=ctx.programs.filter(p=>p.status==='ACTIVE');if(!active.length){message('Crea o activa un programa antes de entregar tarjetas.',true);return;}
    const d=dialog('Entregar tarjeta a un cliente',`<form><div class="sc-form-grid"><label class="sc-wide">Programa<select name="program_id">${active.map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${esc(p.name)} · ${p.stamps_required} sellos</option>`).join('')}</select></label>${field('name','Nombre del cliente','','text','required maxlength="160" autocomplete="name"')}${field('document_id','Documento del cliente','','text','required minlength="3" maxlength="80"')}${field('phone','Celular (opcional)','','tel','maxlength="40"')}${field('email','Correo (opcional)','','email','maxlength="180"')}<label class="sc-check sc-wide"><input type="checkbox" name="consent" required>El cliente autoriza el uso de sus datos para administrar su tarjeta de fidelización.</label><div class="sc-note sc-wide">Usa el mismo documento al registrar compras. Si el cliente ya tiene tarjeta en este programa, recuperaremos su enlace sin duplicar la inscripción.</div></div><footer><button class="sc-primary">Crear y obtener enlace</button></footer></form>`);
    formTask(d,async f=>{const result=await apiCall('/members','POST',{...Object.fromEntries(f),consent:f.has('consent')});d.close();await load();share({...result.member,url:result.url});});
  }
  function share(m){const p=ctx.programs.find(p=>p.id===m.program_id)||m.rules||{};const d=dialog('Comparte la tarjeta',`<div class="sc-preview sc-card">${art(p)}</div><p>Enlace personal de <strong>${esc(m.name)}</strong>. Compártelo solo con su titular; desde él podrá consultar sus sellos y generar el beneficio.</p><a class="sc-share-link" href="${esc(m.url)}" target="_blank" rel="noopener noreferrer">${esc(m.url)}</a><div class="sc-actions"><button id="scCopy">Copiar enlace</button><button id="scNativeShare">Compartir</button><a href="${esc(m.url)}" target="_blank" rel="noopener noreferrer">Abrir tarjeta</a></div>`);d.querySelector('#scCopy').onclick=async()=>{try{await navigator.clipboard.writeText(m.url);d.querySelector('#scDialogMessage').textContent='Enlace copiado.';}catch{d.querySelector('#scDialogMessage').textContent='Selecciona y copia el enlace que aparece arriba.';}};d.querySelector('#scNativeShare').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'Tu tarjeta de sellos',text:`Tu tarjeta de ${ctx.business.name}`,url:m.url});}catch{}}else d.querySelector('#scCopy').click();};}
  function manual(m){const d=dialog('Sellar una visita',`<p>Cliente: <strong>${esc(m.name)}</strong> · ${m.stamps}/${m.rules.stamps_required} sellos.</p><form>${!m.allow_manual?'<label class="sc-check"><input type="checkbox" name="enable_manual" required>Habilitar sellos manuales en este programa, incluidas las tarjetas ya entregadas.</label>':''}<div class="sc-form-grid">${field('reference','Referencia única de la visita','','text','required minlength="3" maxlength="100" placeholder="Ej. VISITA-20261001-001"')}${field('note','Motivo o detalle','','text','required minlength="3" maxlength="500"')}<div class="sc-note sc-wide">Usa este registro para visitas sin compra. Las compras pagadas suman el sello automáticamente; no las registres de nuevo. Los sellos manuales no se contabilizan como ventas.</div></div><footer><button class="sc-primary">Confirmar sello</button></footer></form>`);formTask(d,async f=>{const r=await apiCall(`/members/${m.id}/stamps`,'POST',{...Object.fromEntries(f),enable_manual:f.has('enable_manual')});d.close();await load();message(r.duplicate?'Esta referencia ya estaba registrada. No se agregó otro sello.':'Visita sellada.');});}
  function voidEvent(id){const d=dialog('Anular sello',`<p>El historial se conservará. Si la tarjeta pierde un sello requerido, su ticket sin usar se anulará. Si ya se canjeó, quedará marcado para revisión.</p><form>${field('reason','Motivo de la anulación','','text','required minlength="5" maxlength="500"')}<footer><button>Confirmar anulación</button></footer></form>`);formTask(d,async f=>{await apiCall(`/events/${id}/void`,'POST',Object.fromEntries(f));d.close();await load();message('Sello anulado; historial conservado.');});}
  function exportCsv(){const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';const rows=[['Fecha','Cliente','Documento','Programa','Ciclo','Origen','Venta COP','Anulado','Motivo'],...historyRows.map(e=>[e.created_at,e.name,e.document_key,e.program_name,e.cycle_number,e.source,e.sale_amount,e.voided_at,e.void_reason])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='historial-sellos.csv';a.click();URL.revokeObjectURL(url);}
  root.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const a=button.dataset.action,id=button.dataset.id;
    if(a==='create'||a==='edit')editor(id);if(a==='delete')deleteProgram(id);if(a==='enroll')enrollForm(id);if(a==='share')share(memberRows.find(m=>m.id===id));if(a==='stamp')manual(memberRows.find(m=>m.id===id));if(a==='void')voidEvent(id);if(a==='export')exportCsv();
    if(a.endsWith('-members')){memberOffset=Math.max(0,memberOffset+(a.startsWith('next')?25:-25));loadLists();}if(a.endsWith('-history')){historyOffset=Math.max(0,historyOffset+(a.startsWith('next')?50:-50));loadLists();}
  });
  window.StampCards={open:()=>{shell();load();}};
  if(document.body.dataset.currentView==='stamp-cards')window.StampCards.open();
})();
