(() => {
  const root=document.getElementById('cardApp');
  const token=location.hash.slice(1);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>new Date(v).toLocaleDateString('es-CO');
  const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v||0));
  let data,busy=false;
  async function request(path='',body){const response=await fetch(`/api/public/stamp-cards/${encodeURIComponent(token)}${path}`,{method:body?'POST':'GET',cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'No se pudo cargar la tarjeta. Inténtalo de nuevo.');return result;}
  function ticket(c){const status={REDEEMED:'Beneficio canjeado',CANCELLED:'Ticket anulado',EXPIRED:'Ticket vencido'}[c.ticket_status]||(new Date(c.ticket_expires_at)<new Date()?'Ticket vencido':'Presenta este QR en el negocio');const active=['ACTIVE','CLAIMED'].includes(c.ticket_status)&&new Date(c.ticket_expires_at)>new Date();return `<div class="ticket"><strong>${esc(c.rules.benefit_value.label)}</strong><p>${status}</p>${active?`<img src="${esc(c.qr_image)}" alt="QR de tu beneficio para presentar en el negocio"><small>${esc(c.ticket_code)}</small><a href="${esc(c.qr_image)}" download="mi-beneficio.png">Guardar QR del beneficio</a>`:''}<p class="subtle">Tarjeta ${c.cycle_number} · Vence ${date(c.ticket_expires_at)}</p></div>`;}
  function render(){const c=data.cycles[0];if(!c)throw new Error('Esta tarjeta aún no está disponible.');const r=c.rules,complete=c.stamps>=r.stamps_required,expired=new Date(c.expires_at)<=new Date();const logo=data.business.logo_data_url||data.business.logo_url||'';
    root.innerHTML=`<article class="loyalty-card"><div class="brand">${/^(data:image\/(png|jpeg|webp|gif);base64,|https?:\/\/|\/)/i.test(logo)?`<img src="${esc(logo)}" alt="Logo de ${esc(data.business.name)}">`:''}<span>${esc(data.business.name)}</span></div><p class="eyebrow">Tu fidelidad tiene recompensa</p><h1>${esc(r.name)}</h1><p class="reward">${esc(r.benefit_value.label)}</p>${r.benefit_value.product_scope?`<p>Premio: ${esc(r.benefit_value.product_scope.product_name)}</p>`:''}<div class="dots" role="img" aria-label="${c.stamps} de ${r.stamps_required} sellos">${Array.from({length:r.stamps_required},(_,i)=>`<span class="dot ${i<c.stamps?'filled':''}" aria-hidden="true">${i<c.stamps?'✓':i+1}</span>`).join('')}</div><div class="progress"><span>${c.stamps} de ${r.stamps_required} sellos</span><span>Tarjeta ${c.cycle_number}</span></div></article>
      ${data.identification?`<section class="panel card-identification"><h2>Mi QR de tarjeta</h2><p>Muéstralo en el negocio para que encuentren tu tarjeta y registren tu visita.</p><img src="${esc(data.identification.qr_image)}" alt="QR de identificación de mi tarjeta de sellos"><a href="${esc(data.identification.qr_image)}" download="qr-mi-tarjeta.png">Guardar QR de mi tarjeta</a></section>`:''}
      <section class="panel"><h2>Hola, ${esc(data.name)}</h2><p>${c.claimed_at?'Tu beneficio ya tiene ticket. Guárdalo y preséntalo en el negocio.':expired?'Esta tarjeta venció. Puedes comenzar una nueva si el programa sigue activo.':complete?'¡Completaste tu tarjeta! Ya puedes generar tu beneficio.':`Te faltan ${r.stamps_required-c.stamps} sellos para tu beneficio.`}</p>
      ${data.program.deleted?'<p class="status">Este programa finalizó. Ya no suma sellos ni entrega tarjetas nuevas. Tu historial y los beneficios ganados siguen disponibles hasta su vencimiento.</p>':data.program.status!=='ACTIVE'?'<p class="status">El negocio pausó nuevas tarjetas y sellos. Puedes reclamar un beneficio completo que siga vigente.</p>':''}
      ${c.review_required?'<p class="status error">Se anuló un sello después de emitir el beneficio. Consulta con el negocio.</p>':''}
      ${complete&&!c.claimed_at&&!expired?'<button id="claimBenefit">Generar mi beneficio</button>':''}
      ${c.claimed_at?ticket(c):''}
      ${(c.claimed_at||expired)&&data.program.status==='ACTIVE'?`<details><summary>Condiciones de tu próxima tarjeta</summary><p>${data.program.next_rules.stamps_required} sellos para ${esc(data.program.next_rules.benefit_value.label)}. ${data.program.next_rules.purchase_product?`Compra que incluya ${esc(data.program.next_rules.purchase_product.product_name)}. `:''}Compra mínima ${money(data.program.next_rules.minimum_purchase)}. Vigencia ${data.program.next_rules.card_valid_days} días. ${data.program.next_rules.one_per_day?'Máximo un sello al día.':''}</p><p class="terms">${esc(data.program.next_rules.terms)}</p></details><button id="renewCard" class="secondary">Empezar una nueva tarjeta</button>`:''}
      <p class="message" id="cardMessage" role="status" aria-live="polite"></p><button class="refresh" id="refreshCard">Actualizar mis sellos</button></section>
      <section class="panel"><h2>Así sumas sellos</h2><p>Registra tus compras con el mismo documento con el que recibiste esta tarjeta. Cada compra pagada ${r.purchase_product?`que incluya ${esc(r.purchase_product.product_name)} `:''}${Number(r.minimum_purchase)>0?`desde ${money(r.minimum_purchase)} `:''}suma un sello${r.one_per_day?', con máximo uno por día':''}.</p><p>Al completarla, genera tu beneficio e inicia una nueva tarjeta para seguir sumando. Las compras anteriores a tu inscripción no suman sellos.</p><p>Tarjeta válida hasta ${date(c.expires_at)}. El ticket del beneficio dura ${r.ticket_valid_days} días desde que lo generas y es personal.</p>${r.terms?`<details><summary>Condiciones del negocio</summary><p class="terms">${esc(r.terms)}</p></details>`:''}</section>
      ${data.cycles.some((x,i)=>i&&x.claimed_at)?`<section class="panel"><h2>Mis beneficios anteriores</h2>${data.cycles.filter((x,i)=>i&&x.claimed_at).map(ticket).join('')}</section>`:''}
      <section class="panel"><details><summary>Mi historial reciente</summary><ul class="history">${data.events.map(e=>`<li>${date(e.created_at)} · ${e.source==='SALE'?'Compra registrada':'Visita registrada'} · Tarjeta ${e.cycle_number}${e.voided_at?' · Sello anulado':''}</li>`).join('')||'<li>Tu primer sello está por llegar.</li>'}</ul></details></section>`;
    root.querySelector('#claimBenefit')?.addEventListener('click',()=>mutate('/claim',{cycle_id:c.id}));
    root.querySelector('#renewCard')?.addEventListener('click',()=>mutate('/renew',{}));root.querySelector('#refreshCard').onclick=()=>load();
  }
  async function mutate(path,body){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await request(path,body);await load();}catch(error){root.querySelector('#cardMessage').textContent=/agotado/i.test(error.message)?'Tu beneficio sigue pendiente. El negocio necesita recargar sus tickets; comunícate con él y vuelve a intentarlo.':error.message;}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  async function load(){try{data=await request();render();}catch(error){if(root.querySelector('#cardMessage'))root.querySelector('#cardMessage').textContent=error.message;else root.innerHTML=`<section class="panel"><h1>No pudimos abrir tu tarjeta</h1><p>${esc(error.message)}</p><p>Pide al negocio que te comparta tu enlace personal.</p></section>`;}}
  load();
})();
